FROM node:12.8.1-alpine
LABEL MAINTAINER="Daniel Rataj <daniel.rataj@mall.cz>"

# set a working directory
WORKDIR /app

# copy source code to WORKDIR
COPY admin/ .

# install quasar globally
RUN yarn global add @quasar/cli@1.0.0

# install dependencies
RUN yarn install

# build app
RUN quasar build

# start app to serve static files in /dist directory
CMD [ "npm", "run", "production" ]

# expose port for Node server
EXPOSE 80
